name=input("Enter your name:")
print(name.lower())
print(name.upper())
print(name.title())
print(name.capitalize())
print(name.swapcase())
print(len(name))
print(name.split())
print(name.find("p"))
print(name.count("p"))
print(name.replace("vaishnavi","paranali"))
print(name.strip())
print(name.lstrip())
print(name.rstrip())
print(name.center(60))
print(name.ljust(40))
